# ---------------
# Theme color for customize
# Notice: color value must in double quotes like "#000" or may cause error!
# ---------------

# 语言
language: zh

# 主题配色
theme_color:
  enable: true
  main: "#49B1F5"
  paginator: "#00C4B6"
  button_hover: "#FF7242"
  text_selection: "#00C4B6"
  link_color: "#858585"
  hr_color: "#A4D8FA"
  tag_start_color: "#A4D8FA"
  tag_end_color: "#1B9EF3"
  header_text_color: "#EEEEEE"
  footer_text_color: "#EEEEEE"

# 页面头栏目
# Main menu navigation
menu:
  主页: /
  归档: /archives
  目录: /categories
  标签: /tags
  留言板: /guestbook
  运营历史: /history
  关于作者: /about
  #XXX: /xxx

# 图标（网页tab上方的图标）
# Favicon
# ---------------
favicon: /melody-favicon.ico

# 沉浸式体验配置（未使用）
# PWA
# See https://github.com/JLHwung/hexo-offline
# ---------------
pwa:
  enable: false
  manifest: /manifest.json

  # If you don't want to trouble, just ignore the following things
  # See https://realfavicongenerator.net/
  # theme_color: "#49B1F5"
  # apple_touch_icon: /apple-touch-icon.png
  # favicon_32_32: /favicon-32x32.png
  # favicon_16_16: /favicon-16x16.png
  # mask_icon: /safari-pinned-tab.svg

# 代码高亮主题
# Highlight theme
# ---------------
highlight_theme: light

# 代码换行，开启后代码没有横向滚动条
code_word_wrap: true

# Nav settings
# see the icon_name in fontawesome website.
# And you need to add the `fa` or `fab` prefix by your self.
# ---------------

# 社交
#social:
#icon_name fa: url
#icon_name fab: url
social: 
  github fab: https://github.com/xgyxss
  rss fas: https://yexingshusheng.com/atom.xml
  #search fa: ./search.xml

# algolia_search 搜索
# Algolia search
# ---------------
algolia_search:
  enable: true
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}" # if there are no result
    hits_stats: "${hits} results found in ${time} ms"

# local_seach搜索，想使用需要安装，并对_config.yml文件进行配置
# Local search
# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/third-party-support.html#local-search
# ---------------
local_search:
  enable: true

# MathJax
# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/third-party-support.html#mathjax
# ---------------
mathjax:
  enable: false
  cdn: https://cdn.jsdelivr.net/npm/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# 科学公式（不需要可以不配置）
# KaTeX
# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/third-party-support.html#katex
# ---------------
katex:
  enable: false
  cdn:
    css: https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css
  hide_scrollbar: true

# 点击效果：烟花
# Toggle fireworks (IE >= 10)
# ---------------
fireworks: true

# 百度/谷歌/腾讯统计
# Analysis
# ---------------
baidu_analytics: '8fb1a251f70004c1a430fb7c57039651'

google_analytics: 'G-W160D972F6'

# Tencent_analytics ID
tencent_analytics:

# 前端样式
# stylesheets loaded in the <head>
# ---------------
stylesheets:
  - /css/index.css

  # js导入
# scripts loaded in the end of the body
# ---------------
scripts:
  - /js/utils.js
  - /js/fancybox.js
  - /js/sidebar.js
  - /js/copy.js
  - /js/fireworks.js
  - /js/transition.js
  - /js/scroll.js
  - /js/head.js
 
# 远程导入的CDN资源链接和JS资源链接
# cdn for third-party library
# ---------------
cdn:
  css:
    fontawesome: https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
    fontawesomeV5: https://use.fontawesome.com/releases/v5.15.4/css/all.css
  js:
    anime: https://cdn.jsdelivr.net/npm/animejs@latest/anime.min.js
    jquery: https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
    fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.js
    velocity: https://cdn.jsdelivr.net/npm/velocity-animate@latest/velocity.min.js
    velocity-ui: https://cdn.jsdelivr.net/npm/velocity-ui-pack@latest/velocity.ui.min.js

# 帖子信息设置
# Post info settings
# ---------------
# 侧栏头像
avatar: https://cdn.jsdelivr.net/gh/xgyxss/picgo@main/img/hexo/github-avatar.jpeg

# 顶部图案，也就是banner（壁纸网站选个高清图即可）
top_img: https://cdn.jsdelivr.net/gh/xgyxss/picgo@main/img/hexo/hexo-bg.jpeg # false or url of img
top_img_height: 60 # best range: 60 - 100

# 每篇文章的头部自定义
post_meta:
  date_type: created # created or updated
  categories: true
  tags: true

# 字数统计
# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/additional-package-support.html#word-counting
wordcount:
  enable: true

# 侧栏-文章段落（章节）
toc:
  enable: true
  number: false

# 文章版权声明
post_copyright:
  enable: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# 自动节选（首页摘要多少字，会截断文章或代码，不推荐）
# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/theme-config.html#auto-excerpt
auto_excerpt:
  enable: false
#   length: 50

# 滑动框
# slide
# For reveal.js config, see https://github.com/hakimel/reveal.js#configuration
slide:
  separator: ---
  separator_vertical: --
  charset: utf-8
  theme: black
  codeTheme: monokai
  # optional
  mouseWheel: false
  transition: slide
  transitionSpeed: default
  parallaxBackgroundImage: ""
  parallaxBackgroundSize: ""
  parallaxBackgroundHorizontal: null
  parallaxBackgroundVertical: null
  loop: false
  autoSlide: false
  controlsBackArrows: 'faded'
  controlsLayout: 'bottom-right' # Determines where controls appear, "edges" or "bottom-right"
  progress: true
  showNotes: false
  autoPlayMedia: false
  backgroundTransition: 'fade'

# 文章底部二维码
QR_code:
  - itemlist:
    img: https://cdn.jsdelivr.net/gh/xgyxss/picgo@main/img/hexo/alipay.png
    text: 支付宝打赏
  - itemlist:
    img: https://cdn.jsdelivr.net/gh/xgyxss/picgo@main/img/hexo/wechatpay.png
    text: 微信打赏

# 文章末广告
# adv:
# enable: false
# info:

# 分享系统
# Share System
# ---------------
addThis:
  enable: true
  pubid: ra-6211fe3048a47848

# sharejs:
# enable: false
# disabled_sites:

# 评论系统
# Comments System
# ---------------
disqus:
  enable: false
  #shortname:
  #count:

# laibili:
# enable: false
# uid:

# gitment
# enable: false
# owner:
# repo:
# client_id:
# client_secret:

# gitalk:
#   enable: false
#   client_id:
#   client_secret:
#   repo:
#   owner:
#   admin:

# valine comment system. https://valine.js.org
valine:
  enable: true # if you want use valine,please set this value is true
  appId: zTNuHDTR09rm7hWr9wV6Rhuw-gzGzoHsz  # leancloud application app id
  appKey: xoMEOMRH0kzg9UGJ6koAgm8X  # leancloud application app key
#   notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
#   verify: false # valine verify code (true/false)
  recordip: true # whether record commentor's ip (true/false)
#   pageSize: 10 # comment list page size
  avatar: '' # gravatar style https://valine.js.org/#/avatar
#   lang: zh-cn # i18n: zh-cn/en
  placeholder: Please leave your footprints. # valine comment input placeholder(like: Please leave your footprints )
#   guest_info: nick,mail,link #valine comment header inf
  visitor: false

# vssue:
  # enable: false # Set to true to enable
  # platform: github-v4
  # owner:
  # repo:
  # clientId:
  # clientSecret: # only required for some of the platforms
  # autoCreateIssue: false # Auto create issue on platform (github/...)
  # baseURL: "" # For self-hosted gitlab/bitbucket only, see here: https://vssue.js.org/options/#baseurl
  # perPage: 10 # How much comment/page
  # labels: 'Vssue'

# Footer Settings
# ---------------
# 末尾（时间）
since: 2022

# 自定义链接（一般用来写备案号）
footer_custom_text: <span>It is better to be excellent than to be envious.</span><br><a href="https://beian.miit.gov.cn">鄂ICP备2020021979号</a> 

#ICP:
  #enable: true
  #text: <a href="https://www.miit.gov.cn">鄂ICP备2020021979号</a>

# 卜算子统计
# busuanzi count for PV / UV in site
busuanzi:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i>
  site_uv_footer:
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i>
  site_pv_footer:
  # custom pv span for one page only
  page_pv: true
  page_pv_header: <i class="fa fa-file"></i>
  page_pv_footer:

# canvas_ribbon
# See: https://github.com/hustcc/ribbon.js
canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false

# Sidebar Settings
# ---------------
#links_title: Links
links_title: 友链
links:
  Github: https://github.com
  YouTube: https://www.youtube.com
  Instagram: https://www.instagram.com
  Twitter: https://www.twitter.com

# Follow Me Button
follow:
   enable: true
   url: 'https://github.com/xgyxss'
   #text: 'Follow Me'
   text: '交个朋友吧'

# controls the sidebar showing or hidden in different pages
sidebar_display: post # all/index/post/index-none/post-none/hidden

# 广告
# Ads
# ---------------
# Google Adsense
google_adsense:
  enable: false
  js: //pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client: ca-pub-...........
  enable_page_level_ads: true

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification:

# Bing Webmaster tools verification setting
# See: https://www.bing.com/webmaster/
bing_site_verification:

# Yandex Webmaster tools verification setting
# See: https://webmaster.yandex.ru/
#yandex_site_verification:

# Baidu Webmaster tools verification setting
# See: https://ziyuan.baidu.com/site/
baidu_site_verification:

# 360 Webmaster tools verification setting
# see http://zhanzhang.so.com/
qihu_site_verification:

# avoid baidu transformation
disable_baidu_transformation: true

# 404 Page SubTitle
404Text:

# rss
rss: /atom.xml

# 网易云音乐插件
music:
  enable: true
  #id: 443194241  # 网易云分享的ID
  autoplay: true   # 是否开启自动播放    false为不自动播放

